services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_PORT
        value: 10000
      - key: WEBHOOK_TUNNEL_URL
        value: https://n8n-yourname.onrender.com
      - key: GENERIC_TIMEZONE
        value: Asia/Ho_Chi_Minh
